spring:
  application:
    name: stream-producer
    
  rabbitmq:
    host: 10.99.205.17
    port: 5672
    username: admin
    password: p@ssw0rd

eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka
      