server:
  port: 10000

spring:
  application:
    name: eureka-bus
  rabbitmq:
    host: 10.99.205.17
    port: 5672
    username: admin
    password: p@ssw0rd
    
eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
      
      
management:
  endpoints:
    web:
      exposure:
        include: '*'  