server:
  port: 8081
spring:
  application:
    name: ek-person
    
ek-police: #对应provider的配置文件中的name , 把这个ek-police改成default ， 就会覆盖SpringClientFactory默认的负载类
  ribbon:
    NFLoadBalancerRuleClassName: com.demo.springcloud.first.MyRule

eureka:
  client:
    registry-fetch-interval-seconds: 30 #默认30s,从server抓取provider的注册信息
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      