server:
  port: 8082

spring:
  application:
    name: stream-consumer
  rabbitmq:
    host: 10.99.205.17
    port: 5672
    username: admin
    password: p@ssw0rd
  cloud: 
   stream:
     bindings:
       myInput:
         group: groupA   #消费者分组
    
management: 
  endpoints:
    web:
      exposure: 
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"     

eureka:
  client:
    serviceUrl:
      defaultZone: http://slave1:8761/eureka
      