spring:
  application:
    name: zuul-gateway

server:
  port: 9001
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    sale:
      path: /sale/**
      serviceId: zuul-sale #会使用ribbon进行负载均衡
      