server:
  port: 9000
spring:
  application:
    name: eureka-config-zuul
  cloud:
    discovery:
      enabled: true
      service-id: eureka-config-server
    profile: zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      