server:
  port: 8888
  


  
spring:
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.club.lenovo.com.cn/java/club-confs/
          username: yuezh2@lenovo.com
          password: yuezhihua
          skip-ssl-validation: true
        default-label: lenovo-api/resources/properties   #表示uri路径下的default-config目录下
        health:
          enabled: false
          respositories:
            book-service:
              label: health-test