server:
  port: 8888
 
 
management:
  security:
    enabled: false




#http://localhost:8888/address-dev.properties
#http://localhost:8888/test-dev.properties  (一定要加上-dev,不然不成功)
  
spring:
  #配置服务器加密
  security:
    user:
      name: root
      password: 12345
      
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
        
        #gitlab
#          uri: http://gitlab.club.test.com.cn/java/club-confs.git
#          username: changeusername
#          password: changepassword
#          search-paths: /service-push/resources

         #github
          uri: https://github.com/ht5678/yzh-learn
          #skip-ssl-validation: true
          search-paths: /demo-springcloud-all/S4-l03-springcloud-config-files/service-push/resources
          #default-label: /service-api/resources/properties   #表示uri路径下的default-config目录下
        health:
          respositories:
            test-service:
              label: health-test
              
              

