server:
  port: 9999
spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    username: root
    #password: p@ssw0rd
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2dev?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: localhost
    port: 6379
    #password: root
  session:
    store-type: redis
    timeout: 1800
logging:
  level:
     org:
      sso:
        auth:
          jwt:
            server: debug

