server:
  port: 8761


spring:
  application:
    name: cloud-114-1
  profiles: slave1

eureka:
  client:
    serverUrl:
      defaultZone: http://slave2:8762/eureka
      
---
server:
  port: 8762


spring:
  application:
    name: cloud-114-2
  profiles: slave2

eureka:
  client:
    serverUrl:
      defaultZone: http://slave1:8761/eureka
      

    